title = "config demo"

[server]
basePath = "my-test"
port = "8888"


[db]
[db.local]
driver = "pgx"
dsn = "host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai"
queryLevel = "debug"

[logger]
level = "debug"
filename = ""
maxSize = 10
maxBackups = 5
maxAge = 600
compress = true

